### ISSUE TITLE
Include 'TableId' in filter URL

### ISSUE THREAD

**Issue by fvet** [Drakonian/data-editor-for-bc#2]
Would it be possible to somehow construct a URL to immediately call the Data Editor page, with the 'TableID' as parameter?
E.g. 
https://businesscentral.dynamics.com/?company=My%20Company&page=81000&filter='Table ID' IS '18'

**Comment by Drakonian** [comment]
Hi @fvet 

Could you give me an example of what you need it for? That way, I can perhaps suggest a simpler solution to your problem and add the necessary functionality.

**Comment by fvet** [comment]
We have a small 'Admin' framework that groups various actions for consultants to perform support-related tasks. One of these is a 'Run Any Object' / 'Run Table' feature, building a URL to view table data (e.g. https://businesscentral.dynamics.com/?table=18)

https://businesscentral.dynamics.com/?table=18

I was thinking of adding an 'Edit Table' action, that could call the 'Data Editor' with the a pre-fined table id. (e.g. https://businesscentral.dynamics.com/?page=81000&filter='Table ID' IS '18'. I don't really want to introduce a hard dependency on the 'Data Editor' app, so this is why I was looking into the URL approach.

**Comment by Drakonian** [comment]
@fvet 
Technically it is possible if the main page of the buffer is based on a real record. But it would also slow down the work of loading source records and changing them. 

But I understand why you don't want to add an extra dependency. 
That's why I added a test version of this feature. It contains one bug - you will see an empty confirmation which you will have to close manually. I am not sure if there is a way to close that confirmation page automatically.

Your link will be:
?page=81003&filter='Table Number' is '18'
