### ISSUE TITLE
Idea: Insert entry to log when Data Editor Setup - Enable Log is changed

### ISSUE THREAD

**Issue by RadoArvay** [Drakonian/data-editor-for-bc#28]
I think it could be fine to log an every change in Data Editor Setup related to a logging.
For example: the logging is enabled; someone will turn it off, do some changes in data, and turn it on again. Noone will know that anything happened in data.

BTW: the logging starts with entry number zero, not one - not a bug but little unusual.

**Comment by Drakonian** [comment]
@RadoArvay 
The log has a very negative impact on performance, and the entries also take up space in the database. This is especially noticeable with Modify(), where it is necessary to save the value of each field separately for better detail.

For this reason, the standard Change Log is not enabled by default.

I understand that users might abuse this setting. However, such cases of intentional sabotage are quite rare, so I don't think this is a common problem.

In any case, you can devise a control mechanism so that only certain users can enable or disable this setting. This should only be possible for privileged users.

Regarding Entry No., that's a good point. It's because I'm using NumberSequence() to get the number, and it starts at 0 by default. I don't think this is a critical issue, but I will fix it anyway.

**Comment by Drakonian** [comment]
https://github.com/Drakonian/data-editor-for-bc/commit/591de20fef776777d68fbe9c41e3a0c2af234307
