### ISSUE TITLE
Error when renaming a record

### ISSUE THREAD

**Issue by Erwin-k** [Drakonian/data-editor-for-bc#29]
The below line code doesn't add anything to the functionality, but rather causes an error when trying to rename a record

https://github.com/Drakonian/data-editor-for-bc/blob/fd3b37edc3967bb9df1243b019b53eff0e20c117/Codeunits/Cod81001.DETDataEditorMgt.al#L135

**Comment by Drakonian** [comment]
Which version of BC do you use?

**Comment by Erwin-k** [comment]
I use BC24 Online. 
When trying to change the field Positive in the Reservation Entry table for Yes to No, the error message is:
![image](https://github.com/user-attachments/assets/6b366288-e8f1-4dc4-8f69-7f1cf0b9f188)

Error details:
If requesting support, please provide the following details to help troubleshooting:

Error message: 
The type NavBoolean is unknown.

Page Reservation Entry has to close.

Internal session ID: 
27deaf52-812b-4ce6-a109-440b8cbc577e

Application Insights session ID: 
759a4642-e795-480b-88b1-898eafd983b3

Client activity id: 
e5471d86-f1cd-4b4e-b5c9-9e23563ee562

Time stamp on error: 
2024-08-29T09:42:45.1937935Z

User telemetry id: 
ee14ad42-5112-4a0f-9f64-ffd0f6123172

AL call stack: 
"DET Data Editor Mgt."(CodeUnit 81001).RenamePKField line 30 - Data Editor Tool by Volodymyr Dvernytskyi
"DET Data Editor Buffer"(Page 81000).OnValidateField line 18 - Data Editor Tool by Volodymyr Dvernytskyi
"DET Data Editor Buffer"(Page 81000)."Text Value 3 - OnValidate"(Trigger) line 2 - Data Editor Tool by Volodymyr Dvernytskyi

**Comment by Drakonian** [comment]
@Erwin-k 

Let's start by clarifying that the line you mentioned is not useless at all; in fact, it's essential, and I'll explain why. 
The Table 81000 "DET Data Editor Buffer" consists of many text fields. To display data from any other table, a trick is used where all fields are converted to text format. Converting data types to text is necessary because there is no such data type as Variant in a table, and we don't know what type the fields will be. Of course, we could have created 300 fields of each type in Business Central, but that would have significantly reduced performance, as the table is already overloaded.
https://github.com/Drakonian/data-editor-for-bc/blob/607fcb2a37af1c163c47b96b5f5ae68d9bdd0d48/Tables/Tab81000.DETDataEditorBuffer.al#L1

This trick creates an additional problem: correctly transforming the text back to the appropriate data type. This is easier to do when using DrillDown (the three dots on the textbox) because, in that case, we use a type matrix, and the UI loads with the correct data type, limiting the user to that field (they cannot enter text in a number field, for example). However, it’s a bit more complicated when entering text directly into a field, as automatic transformation is required. This is just a bit of background on why things are set up this way.

Your error was related to transforming text into Boolean for Rename. This error was present in both the textbox and the UI matrix. Here, you can see the fixes:
https://github.com/Drakonian/data-editor-for-bc/commit/607fcb2a37af1c163c47b96b5f5ae68d9bdd0d48

If you're curious about the purpose of the line you asked about, it's used to transform the incoming value (which could be text) into the corresponding data type using the TempRecRef variable. By assigning the new Primary Key value to TempRecRef, we store this change in memory in the correct data type. The Rename itself doesn't happen at this point, but the values are now in the correct format.
https://github.com/Drakonian/data-editor-for-bc/blob/607fcb2a37af1c163c47b96b5f5ae68d9bdd0d48/Codeunits/Cod81001.DETDataEditorMgt.al#L135

In the next step, all the Primary Key values (including the new one) are taken from TempRecRef for the actual Rename in RecordRef.
https://github.com/Drakonian/data-editor-for-bc/blob/607fcb2a37af1c163c47b96b5f5ae68d9bdd0d48/Codeunits/Cod81001.DETDataEditorMgt.al#L137

Why? Because there never was, and still isn't, an object like "List of [Variant]" that could solve this problem more elegantly. I even wrote about this in one of my articles you can check it out:
https://vld-nav.com/work-with-rename-method

As you can see, there are many limitations in the Business Central platform that dictate, at first glance, strange and seemingly incomprehensible solutions.

In any case, the problem has been fixed.

**Comment by Erwin-k** [comment]
Ah ok, I get it. Thanks for the response and the fix.

Ran into the described issue as well over a decade ago. Solved it using the code below (for your entertainment)

    local procedure CheckValue(var vTxtValue: Text): Text
    var
        FieldRec: Record "Field";
        RecRef: RecordRef;
        FldRef: FieldRef;
        DateFormulaVar: DateFormula;
        DateFormulaTxt: Text;
        OptionsTxt: Text[1024];
        RecID: RecordID;
        GuidVar: Guid;
        NoOfOptions: Integer;
        Counter: Integer;
        NoFieldNo: Label 'First select a field';
        WrongType: Label 'Changing a field of type %1 has not been implemented yet';
    begin
        if (TableNo = 0) or (FieldNo = 0) then
            Error(NoFieldNo);
        FieldRec.Get(TableNo, FieldNo);

        RecRef.Open(TableNo);
        FldRef := RecRef.Field(FieldNo);
        case FieldRec.Type of
            FieldRec.Type::TableFilter,
          FieldRec.Type::OemText,
          FieldRec.Type::Binary,
          FieldRec.Type::BLOB,
          FieldRec.Type::OemCode,
          FieldRec.Type::BigInteger,
          FieldRec.Type::Duration:
                Error(WrongType, Format(FieldRec.Type));

            FieldRec.Type::RecordID:
                if Evaluate(RecID, vTxtValue) then
                    FldRef.SetRange(RecID);

            FieldRec.Type::GUID:
                if Evaluate(GuidVar, vTxtValue) then
                    FldRef.SetRange(GuidVar);

            FieldRec.Type::Date,
          FieldRec.Type::DateTime:
                FldRef.SetFilter(vTxtValue);
            FieldRec.Type::Time,
          FieldRec.Type::DateFormula,
          FieldRec.Type::Text,
          FieldRec.Type::Code:
                FldRef.SetFilter(vTxtValue);
            FieldRec.Type::Decimal,
          FieldRec.Type::Integer,
          FieldRec.Type::Boolean:
                FldRef.SetRange(vTxtValue);

            FieldRec.Type::Option:
                begin
                    if Evaluate(Counter, vTxtValue) then begin
                        OptionsTxt := FldRef.OptionCaption;
                        vTxtValue := SelectStr(Counter, OptionsTxt);
                    end;
                    FldRef.SetFilter(vTxtValue);
                end;
        end;

        exit(FldRef.GetFilter);
    end;

**Comment by Drakonian** [comment]
@Erwin-k 

I have this as well 😄 

https://github.com/Drakonian/data-editor-for-bc/blob/607fcb2a37af1c163c47b96b5f5ae68d9bdd0d48/Codeunits/Cod81001.DETDataEditorMgt.al#L778
